version: '3'
    
services:
    #nginx
    nginx:
        image: nginx:latest
        ports:
            - "8887:80"
        volumes:
            - ./hosts:/etc/nginx/conf.d/
            - ./www:/var/www
            - ./logs:/var/log/nginx
        links:
            - php

    #php
    php:
        build: ./images/php
        links:
            - mysql
        volumes:
            - ./www:/var/www

    #mysql
    mysql:
        image: mysql
        #ports:
        #    - "3307:3306"
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root